#!/usr/bin/env bash

MY_PATH="`dirname \"$0\"`"

#change Info.plist
sed -e '8s#.*#<string>launcher</string>#' -i '' ${MY_PATH}/Displaz.app/Contents/Info.plist

#copy launcher executable into MacOS bundle
cp ${MY_PATH}/launcher ${MY_PATH}/Displaz.app/Contents/MacOS; exit;
